### ISSUE TITLE
Frontend: not all fields are visible

### ISSUE THREAD

**Issue by tgoelles** [jmcook1186/biosnicar-py#79]
The three buttons block some elements of the UI. See image. 
Tested in firefox, and chrome

<img width="964" alt="image" src="https://user-images.githubusercontent.com/28436117/169315388-a9b0f4de-52d3-4fc6-b1bb-addd0a61197c.png">

I don't know much about web-development but isn't flask alone enough for the job? Why the need for javascript?

**Comment by jmcook1186** [comment]
oh strange. looks ok for me, but I have only tested on my specific set up. The frontend is very rough and could do with some work from someone that knows what they are doing.

Only reason for JS frontend was because I know a (little) bit of React and was the path of least resistance for me to whip up a PoC. 

Please have a hack at it - my version looks ugly and is very awkward to containerize and/or deploy publicly because of the dual Flask/React servers interoperating.

**Comment by tgoelles** [comment]
Here is a proof of concept. Purely in python made with streamlit. Just one file with 150 lines. Its fully interactive, so the changes in the input are immediately visible in the plot. The plot is also interactive made with plotly. 

There is also a light theme which changes according to the system settings.

<img width="1452" alt="Screenshot 2022-05-26 at 09 49 42" src="https://user-images.githubusercontent.com/28436117/170443505-6dedab47-180d-4bdf-be72-beda77b414f2.png">

**Comment by tgoelles** [comment]
fixed with streamlit
