### ISSUE TITLE
TOOM or ADD_DOUBLE solvers?

### ISSUE THREAD

**Issue by Viankcor** [jmcook1186/biosnicar-py#83]
Sorry, I'm new to the model. I've been running the model from /src/biosnicar/snicar_driver.py and in the imputs.yaml file I can't find the option to select the type of solver I want. Note: I want to use the ADD_DOUBLE solver.

Please help.

**Comment by jmcook1186** [comment]
Hi @Viankcor, thanks for your interest in the model. The solvers are included as separate functions in the model, so instead of choosing one or other in `inputs.yaml` you first configure your input file and then invoke either adding_doubling_solver()` or `toon_solver` in your driver script.

For example

```python
# run the desired radiative transfer solvers

outputs1 = adding_doubling_solver(tau, ssa, g, L_snw, ice, illumination, model_config)

outputs2 = toon_solver(tau, ssa, g, L_snw, ice, illumination, model_config, rt_config)

```

**Comment by jmcook1186** [comment]
closing as complete
